pre_install(){
    systemctl start docker
}

post_install(){
    docker pull qzwlecr/netease-cloud-music-docker-version
    echo "[WARNING!]Please use \"usermod -a -G docker USERNAME\" to make sure you can access docker"
}

pre_upgrade(){
    systemctl start docker
}

post_upgrade(){
    docker pull qzwlecr/netease-cloud-music-docker-version
}

pre_remove(){
    systemctl start docker
}

post_remove(){
    docker rmi -f qzwlecr/netease-cloud-music-docker-version
}
